version: '3.4'

services:
  teacher_nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: examking_teacher_nginx
    depends_on:
      - teacher_build
    ports:
      - 8082:80
    restart: "always"
    volumes:
      - dist:/var/www/html:rw
      - ./docker/nginx/logs:/var/log/nginx:rw
      - ./docker/nginx/vhost:/etc/nginx/conf.d/:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  teacher_build: 
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile
    container_name: examking_teacher_build
    volumes:
      - ./:/home/examking:rw
      - dist:/home/examking/dist
      - node_modules:/home/examking/node_modules

volumes: 
  node_modules:
  dist:

networks: # 创建新的网络类型
  examking_net:
    driver: bridge  # 网络方式：桥接或集群