version: '3.4'

services:
  teacher_nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: examking_teacher_nginx
    depends_on:
      - teacher_build
    ports:
      - 8082:80
    restart: "always"
    volumes:
      - admin_dist:/var/www/html:rw
  teacher_build: 
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile
    container_name: examking_teacher_build
    volumes:
      - admin_dist:/home/examking_teacher/dist
      - admin_node_modules:/home/examking_teacher/node_modules

volumes: 
  admin_node_modules:
  admin_dist:

networks: # 创建新的网络类型
  examking_net:
    driver: bridge  # 网络方式：桥接或集群