version: '3.4'

services:
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    image: ek_teacher_web:${VERSIONTAG}
    ports:
      - 8082:80
    restart: "always"
    networks:
      - server_net
    volumes:
      - node_modules:/build:rw

volumes: 
  node_modules:

networks: # 创建新的网络类型
  server_net:
    external:
      name: ek_server_eknet